# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
  ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
  command: >
    php bin/console server:run 0.0.0.0:8000
